source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SLSocialShare_Example', :exclusive => true do
  pod "SLSocialShare", :path => "../"
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'google-plus-ios-sdk'
  pod 'InstagramKit'
  pod 'MBProgressHUD'
  pod ‘FHSTwitterEngine'

end

target 'SLSocialShare_Tests', :exclusive => true do
  pod "SLSocialShare", :path => "../"

  pod 'FBSnapshotTestCase'
end
