source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SLSocialShare_Example', :exclusive => true do
  pod "SLSocialShare", :path => "../"
end

target 'SLSocialShare_Tests', :exclusive => true do
  pod "SLSocialShare", :path => "../"

  pod 'FBSnapshotTestCase'
end
